import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ResearchBriefBody } from "@/components/research/brief-body";
import { FeedbackPrompt } from "@/components/feedback/feedback-prompt";
import { BriefViewTracker } from "@/components/analytics/brief-view-tracker";
import { getBriefById, extractProofSources } from "@/lib/research/briefs";
import { prisma } from "@/lib/db";

type BriefPageProps = {
  params: Promise<{ id: string }>;
};

const isValidObjectId = (id: string): boolean => {
  return /^[a-f\d]{24}$/i.test(id);
};

export async function generateMetadata({ params }: BriefPageProps): Promise<Metadata> {
  const { id } = await params;

  // Validate ObjectId format to prevent database errors
  if (!isValidObjectId(id)) {
    return {
      title: "Invalid Brief",
      description: "The requested brief could not be found.",
    };
  }

  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return {
      title: "Research brief",
      description: "Detailed research brief generated by Idea Analyzer.",
    };
  }

  const brief = await getBriefById(id);
  if (!brief || brief.userId !== session.user.id) {
    return {
      title: "Research brief",
      description: "Detailed research brief generated by Idea Analyzer.",
    };
  }

  const title = brief.idea?.title ?? "Research brief";
  const description = brief.content?.description ?? "Structured research brief.";

  return {
    title: `${title} | Research Brief`,
    description,
    openGraph: {
      title: `${title} | Research Brief`,
      description,
    },
    twitter: {
      card: "summary_large_image",
      title: `${title} | Research Brief`,
      description,
    },
  };
}

export default async function BriefPage({ params }: BriefPageProps) {
  const { id } = await params;

  // Validate ObjectId format to prevent database errors
  if (!isValidObjectId(id)) {
    notFound();
  }

  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    redirect("/login?callbackUrl=%2Fbrief%2F" + encodeURIComponent(id));
  }

  const brief = await getBriefById(id);
  if (!brief) {
    notFound();
  }
  if (brief.userId !== session.user.id) {
    redirect("/dashboard?error=forbidden");
  }

  const { content } = brief;
  const proofSources = extractProofSources(content);
  const generatedOn = new Intl.DateTimeFormat(undefined, {
    dateStyle: "full",
    timeStyle: "short",
  }).format(new Date(brief.completedAt ?? brief.createdAt));
  const existingFeedback = await prisma.feedback.findFirst({
    where: {
      briefId: brief.id,
      userId: session.user.id,
    },
    select: {
      rating: true,
      comments: true,
      sectionRatings: true,
    },
  });

  return (
    <div className="min-h-screen">
      <BriefViewTracker briefId={brief.id} userId={session.user.id} />
      <header className="border-b border-border/40 bg-gradient-to-b from-background/95 to-background/60 backdrop-blur-sm">
        <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-6 py-12">
          <div className="flex flex-col gap-4">
            <p className="text-xs font-semibold uppercase tracking-[0.3em] text-accent-coral">
              Research
            </p>
            <h1 className="bg-gradient-to-br from-foreground to-foreground-secondary bg-clip-text text-4xl font-bold tracking-tight text-transparent sm:text-4xl">
              {brief.idea?.title ?? "Untitled idea"}
            </h1>
            <p className="text-sm text-muted-foreground">
              Generated on {generatedOn}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-3">
            {content.industryTag && (
              <Badge variant="default" className="border-[color:var(--glass-border)]  backdrop-blur-sm">
                {content.industryTag}
              </Badge>
            )}
            {content.businessType && (
              <Badge variant="default" className="border-[color:var(--glass-border)] backdrop-blur-sm">
                {content.businessType}
              </Badge>
            )}
          </div>
          <p className="max-w-3xl text-base leading-relaxed text-muted-foreground">{content.description}</p>
        </div>
      </header>

      <main className="mx-auto flex w-full max-w-7xl flex-col gap-10 px-6 py-12">
        <ResearchBriefBody content={content} proofSources={proofSources} />

        <FeedbackPrompt
          briefId={brief.id}
          initialFeedback={
            existingFeedback
              ? {
                  rating: existingFeedback.rating,
                  comments: existingFeedback.comments ?? "",
                }
              : undefined
          }
        />

        <div className="glass-strong rounded-[32px] border border-[color:var(--glass-border)] bg-[color:var(--glass-surface)] p-8 shadow-lg transition hover:shadow-xl space-y-4">
          <div>
            <h3 className="text-2xl font-semibold text-foreground">Need another brief?</h3>
            <p className="text-sm text-muted-foreground">
              Continue iterating with our conversational assistant to validate your next idea.
            </p>
          </div>
          <Button asChild size="lg" className="shadow-md">
            <Link href="/dashboard/analyze">Generate Another Brief</Link>
          </Button>
        </div>
      </main>
    </div>
  );
}
